### ISSUE TITLE
Hidden exception due to hidden, removed preferences nodes

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#108]
Using eMoflon 2.21.0 (which has been deployed with the current moflon target definition), we still face problems with spurious IllegalStateExceptions such as the following, which occurs when checking out the example workspace *Handbook Part 4 Start*. I guess the problem is some missing guard in org.gervarro.eclipse.workspace.autosetup.ProjectAutoConfigurator.removed(ProjectAutoConfigurator.java:129).
```

java.lang.IllegalStateException: Preference node ".org.eclipse.jdt.core.external.folders" has been removed.
	at org.eclipse.core.internal.preferences.EclipsePreferences.checkRemoved(EclipsePreferences.java:164)
	at org.eclipse.core.internal.preferences.EclipsePreferences.parent(EclipsePreferences.java:828)
	at org.gervarro.eclipse.workspace.autosetup.ProjectAutoConfigurator.removed(ProjectAutoConfigurator.java:129)
	at org.eclipse.core.internal.preferences.EclipsePreferences$1.run(EclipsePreferences.java:784)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.preferences.EclipsePreferences.fireNodeEvent(EclipsePreferences.java:787)
	at org.eclipse.core.internal.preferences.EclipsePreferences.removeNode(EclipsePreferences.java:994)
	at org.eclipse.core.internal.preferences.EclipsePreferences.removeNode(EclipsePreferences.java:976)
	at org.eclipse.core.internal.preferences.EclipsePreferences.removeNode(EclipsePreferences.java:981)
	at org.eclipse.core.internal.resources.ProjectPreferences.removeNode(ProjectPreferences.java:214)
	at org.eclipse.core.internal.resources.ProjectPreferences.deleted(ProjectPreferences.java:125)
	at org.eclipse.core.internal.resources.ProjectPreferences.deleted(ProjectPreferences.java:140)
	at org.eclipse.core.internal.resources.Resource.deleteResource(Resource.java:849)
	at org.eclipse.core.internal.resources.Project.deleteResource(Project.java:329)
	at org.eclipse.core.internal.resources.ResourceTree.deletedProject(ResourceTree.java:173)
	at org.eclipse.core.internal.resources.ResourceTree.internalDeleteProject(ResourceTree.java:444)
	at org.eclipse.core.internal.resources.ResourceTree.standardDeleteProject(ResourceTree.java:850)
	at org.eclipse.core.internal.resources.Resource.unprotectedDelete(Resource.java:1836)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:782)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:324)
	at org.eclipse.jdt.internal.core.ExternalFoldersManager.cleanUp(ExternalFoldersManager.java:226)
	at org.eclipse.jdt.internal.core.JavaModelManager.saving(JavaModelManager.java:4451)
	at org.eclipse.core.internal.resources.SaveManager.executeLifecycle(SaveManager.java:389)
	at org.eclipse.core.internal.resources.SaveManager$1.run(SaveManager.java:198)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.resources.SaveManager.broadcastLifecycle(SaveManager.java:201)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1186)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1165)
	at org.eclipse.core.internal.resources.DelayedSnapshotJob.run(DelayedSnapshotJob.java:52)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gervarro** [comment]
Are modules from the http://gervarro.org/eclipse-utils/integration-2.0.0/ update site installed?

I think that the above-mentioned code should not run at all, if a clean eMoflon (with the 3 embedded plugins and without the rest from the eclipse-utils update site) is installed. The 3 embedded modules (i.e., org.gervarro.eclipse.task, org.gervarro.eclipse.workspace.util, org.gervarro.eclipse.workspace.autosetup) should not invoke any code from the class ProjectAutoConfigurator. ProjectAutoConfigurator is only started, if one of the remaining plugins is explicitly installed for your Eclipse.

**Comment by RolandKluge** [comment]
Yes, the integration-2.0.0 update site contains one feature and all of its plugins were installed.

I have now disabled all but the 3 embedded plugins using the Content tag of the Edit Target Definition dialog
