### ISSUE TITLE
NumberFormatException for LiteralExpression Double.MAX_VALUE during code generation

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#12]
_From @RolandKluge on May 26, 2015 15:53_

Using *Double.MAX_VALUE* as LiteralExpression causes an exception during code generation.

ERROR [handlers.EMoflonBuildJob::67]: Unable to Clean and Build: Cause: NumberFormatException: For input string: "MAX_VALUE"
StackTrace: java.lang.NumberFormatException: For input string: "MAX_VALUE"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at java.lang.Double.valueOf(Unknown Source)
	at org.eclipse.emf.ecore.impl.EcoreFactoryImpl.createEDoubleFromString(EcoreFactoryImpl.java:795)
	at org.eclipse.emf.ecore.impl.EcoreFactoryImpl.createFromString(EcoreFactoryImpl.java:134)
	at LiteralExprResolver.impl.ConstantTransformerImpl.pattern_ConstantTransformer_0_20_greenFBBB(ConstantTransformerImpl.java:577)
	...
(Full stacktrace at: http://pastebin.com/M2A0GKbb)

eMoflon version: 1.7.7

_Copied from original issue: eMoflon/emoflon#448_

**Comment by RolandKluge** [comment]
FYI @fdeckwerth

**Comment by RolandKluge** [comment]
_From @gervarro on May 27, 2015 12:47_

Issue fixed in the main validation by commits #1281 on the Validation.eap file and #3987 in the LiteralExpressionResolver project. I leave the issue open, as Fred also wanted to fix something in connection with this issue.

**Comment by RolandKluge** [comment]
@fdeckwerth Can we close this issue now?

**Comment by RolandKluge** [comment]
Closing due to missing activity.
