### ISSUE TITLE
Unable to Set Classpath Variable in CMoflon

### ISSUE THREAD

**Issue by davidgiessing** [eMoflon/emoflon-tool#144]
13:32:37 ERROR [utilities.WorkspaceHelper::31] - Unable to set classpath variable Reason:
Java Model Exception: Java Model Status [TCLanguage does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:556)
	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2378)
	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:1909)
	at org.eclipse.jdt.internal.core.JavaProject.getRawClasspath(JavaProject.java:1931)
	at org.moflon.core.utilities.WorkspaceHelper.addContainerToBuildPath(WorkspaceHelper.java:497)
	at org.moflon.core.utilities.WorkspaceHelper.addContainerToBuildPath(WorkspaceHelper.java:486)
	at org.moflon.util.plugins.PluginProducerWorkspaceRunnable.run(PluginProducerWorkspaceRunnable.java:64)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.cmoflon.ide.core.runtime.ResourceFillingMocaCMoflonTransformation.handleOpenProject(ResourceFillingMocaCMoflonTransformation.java:335)
	at org.cmoflon.ide.core.runtime.ResourceFillingMocaCMoflonTransformation.handleOutermostPackage(ResourceFillingMocaCMoflonTransformation.java:128)
	at org.moflon.core.mocatomoflon.impl.ExporterImpl.pattern_Exporter_22_7_PostprocessOutermostPackage_expressionBBB(ExporterImpl.java:5419)
	at org.moflon.core.mocatomoflon.impl.ExporterImpl.mocaToEcore(ExporterImpl.java:1935)
	at org.cmoflon.ide.core.runtime.builders.CMoflonMetamodelBuilder.processResource(CMoflonMetamodelBuilder.java:75)
	at org.cmoflon.ide.core.runtime.builders.CMoflonMetamodelBuilder.visit(CMoflonMetamodelBuilder.java:114)
	at org.cmoflon.ide.core.runtime.builders.CMoflonMetamodelBuilder.visit(CMoflonMetamodelBuilder.java:129)
	at org.cmoflon.ide.core.runtime.builders.CMoflonMetamodelBuilder.visit(CMoflonMetamodelBuilder.java:131)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at org.moflon.ide.core.runtime.builders.AbstractBuilder.build(AbstractBuilder.java:60)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) @RolandKluge

**Comment by RolandKluge** [comment]
I think that the best solution is to create a custon CMoflonProjectProducingRunnable instead of changing the standard PluginProducingWorkspaceRunnable. The reason is that cMoflon projects are not only *no* Java projects, they are also *no* plugin projects.

The point in the code to change is https://github.com/eMoflon/emoflon-tool/blob/giessing-cmoflon/org.moflon2contiki.ide.core/src/org/cmoflon/ide/core/runtime/ResourceFillingMocaCMoflonTransformation.java#L335
