### ISSUE TITLE
DanglingHREFException on code generation for TGG

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#22]
_From @mabilov on July 30, 2015 9:28_

The exception occurs on execution of code generation for TGG project.

11:24:00 ERROR [handlers.EMoflonBuildJob::67] - Unable to Clean and Build: Cause: DanglingHREFException: The object 'TGGLanguage.impl.TGGLinkVariableImpl@49541939 (name: __lastInDef) (bindingOperator: CHECK_ONLY, bindingSemantics: MANDATORY)' is not contained in a resource.
StackTrace: org.eclipse.emf.ecore.xmi.DanglingHREFException: The object 'TGGLanguage.impl.TGGLinkVariableImpl@49541939 (name: __lastInDef) (bindingOperator: CHECK_ONLY, bindingSemantics: MANDATORY)' is not contained in a resource.
    at org.eclipse.emf.ecore.xmi.impl.XMLHelperImpl.handleDanglingHREF(XMLHelperImpl.java:754)
    at org.eclipse.emf.ecore.xmi.impl.XMLHelperImpl.getURIFragment(XMLHelperImpl.java:725)
    at org.eclipse.emf.ecore.xmi.impl.XMLHelperImpl.getIDREF(XMLHelperImpl.java:747)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveIDRefMany(XMLSaveImpl.java:2023)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1370)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedMany(XMLSaveImpl.java:2417)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1553)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedSingle(XMLSaveImpl.java:2403)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1547)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedMany(XMLSaveImpl.java:2417)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1553)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedSingle(XMLSaveImpl.java:2403)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1547)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedMany(XMLSaveImpl.java:2417)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1553)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedMany(XMLSaveImpl.java:2417)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1553)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedMany(XMLSaveImpl.java:2417)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1553)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.writeTopObject(XMLSaveImpl.java:683)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.traverse(XMLSaveImpl.java:591)
    at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.save(XMLSaveImpl.java:251)
    at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doSave(XMLResourceImpl.java:389)
    at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1430)
    at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:999)
    at org.moflon.eclipse.resource.SDMEnhancedEcoreResource.save(SDMEnhancedEcoreResource.java:134)
    at org.moflon.ide.core.runtime.codegeneration.IntegrationCodeGenerator.processTGG(IntegrationCodeGenerator.java:273)
    at org.moflon.ide.core.runtime.codegeneration.IntegrationCodeGenerator.generateCode(IntegrationCodeGenerator.java:86)
    at org.moflon.ide.core.util.BuilderHelper.generateCodeInOrder(BuilderHelper.java:96)
    at org.moflon.ide.ui.admin.handlers.EMoflonBuildJob.run(EMoflonBuildJob.java:62)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

_Copied from original issue: eMoflon/emoflon#534_

**Comment by RolandKluge** [comment]
_From @mabilov on July 30, 2015 11:5_

Apparently the problem occurs if I have "check only" self reference edge. So for example, when I need to check whether class A has a reference to itself. But when I need to create a self reference, the code generation succeeds.

**Comment by RolandKluge** [comment]
_From @erhanleblebici on July 30, 2015 12:59_

could you provide an eap to reproduce the error?

**Comment by RolandKluge** [comment]
_From @mabilov on July 30, 2015 13:3_

Yes, sure. You can download it here:
https://mega.nz/#!2IEVxaKT!2hVhO9EkMOdXh7JYyJcfo1gRfAKrHSL9ekbt7_JBNG4

**Comment by RolandKluge** [comment]
_From @erhanleblebici on July 31, 2015 10:52_

Thanks for the eap. I could find out that the problem is only in model generator use case in which you are not interested anyway. I could not solve the issue yet but I have a suggestion such that you can keep yorking with your TGG:

Change the build mode of your TGG to FORWARD_BACKWARD as described in the screenshot. This way you eliminate the model generator and its bugs from your project:

![screenshot 2015-07-31 12 42 37](https://cloud.githubusercontent.com/assets/11506522/9005887/446381fe-3782-11e5-8ee2-6023afdfe4af.png)

@anthonyanjorin this seems to be a bug very deep in model generator. The eap is in our eMoflon folder: https://www.dropbox.com/s/8oj7f3x68vf87n0/Issue534.eap?dl=0

**Comment by RolandKluge** [comment]
_From @mabilov on July 31, 2015 10:55_

Ok, thank you
