### ISSUE TITLE
NullPointerException in freshly created Integration Project

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#336]
With eMoflon 3.2.0, the code generation for freshly created Integration Projects may fail with a stacktrace similar to the following one

```
java.lang.NullPointerException occurred during eMoflon code generation. 
Message: 'null'. Stacktrace:
java.lang.NullPointerException
    at org.moflon.codegen.eclipse.MoflonCodeGenerator.getFullProjectName(MoflonCodeGenerator.java:221)
    at
org.moflon.codegen.eclipse.MoflonCodeGenerator.processResource(MoflonCodeGenerator.java:68)
    at
org.moflon.emf.build.GenericMoflonProcess.run(GenericMoflonProcess.java:111)
    at
org.moflon.ide.core.runtime.builders.RepositoryBuilder.processResource(RepositoryBuilder.java:133)
    at
org.moflon.ide.core.runtime.builders.IntegrationBuilder.processResource(IntegrationBuilder.java:92)
    at
org.gervarro.eclipse.workspace.util.RelevantElementCollectingBuilder.postprocess(RelevantElementCollectingBuilder.java:54)
    at
org.moflon.core.build.AbstractVisitorBuilder.postprocess(AbstractVisitorBuilder.java:50)
    at
org.gervarro.eclipse.workspace.util.RelevantElementCollectingBuilder.postprocess(RelevantElementCollectingBuilder.java:1)
    at
org.gervarro.eclipse.workspace.util.VisitorDrivenProjectBuilder.build(VisitorDrivenProjectBuilder.java:51)
    at
org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at
org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
    at
org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
    at
org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
```

**Comment by RolandKluge** [comment]
Workaround:
1. Open the *moflon.properties.xmi* of the affected integration project using the EMF Editor in Eclipse
2. Navigate to root element ("Moflon Properties Container")
3. Right-click, "New Child", Meta Model Project
4. Save and build again.
