### ISSUE TITLE
Visualization: Problems with MocaToMoflonAttributeConstrTestGenerator in TestWorkspace_Misc 

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#34]
_From @RolandKluge on February 16, 2016 9:45_

When visualizing 'ActivityNode9_NAC_2', an exception is thrown:

```
java.lang.ClassCastException: 
        org.moflon.tgg.language.algorithm.impl.TempOutputContainerImpl 
        cannot be cast to 
        org.moflon.ide.visualization.dot.language.DirectedGraph
at org.moflon.ide.visualisation.dot.language.EMoflonDiagramTextProvider.runTrafo(EMoflonDiagramTextProvider.java:233)
at org.moflon.ide.visualisation.dot.language.EMoflonDiagramTextProvider.runBatch(EMoflonDiagramTextProvider.java:254)
at org.moflon.ide.visualisation.dot.language.EMoflonDiagramTextProvider.modelToDot(EMoflonDiagramTextProvider.java:173)
```

_Copied from original issue: eMoflon/emoflon#667_

**Comment by RolandKluge** [comment]
Find attached the corresponding Ecore file (The problems seems to be around line 232):
[MocaToMoflonAttributeConstrTestGenerator.ecore.txt](https://github.com/eMoflon/emoflon/files/132192/MocaToMoflonAttributeConstrTestGenerator.ecore.txt)

**Comment by RolandKluge** [comment]
_From @anthonyanjorin on February 17, 2016 11:2_

As discussed with @erhanleblebici we should improve error messages concerning multiple roots or no result.  The message above is extremely cryptic and useless for users.

**Comment by RolandKluge** [comment]
_From @anthonyanjorin on February 21, 2016 11:19_

@RolandKluge : I've checked the .ecore file and found out the problem.  The current visualization does not work for ApplicationConditions from the SDM metamodel.

I'm a bit unsure what to do here -- we have two means of representing NACs (1) as simple NACs (that was the only thing CodeGen2 could do), and (2) as ApplicationConditions, which can be more complex.

As I've never used them before I simply do not know how far the support for them is.  If they are well supported we should clean up our metamodel and remove the old form of NACs.  This has a lot of consequences though:  our TGG-tooling generates the old NACs, the visualization only works for the old NACs, and MOSL only supports the old NACs (syntax and tooling).

This is a bit of a problem really -- in general we (Erhan and I) tend not to think of the latest features from Fred (so complex NACs and complex attribute conditions for SDMs).

FYI:  @erhanleblebici

**Comment by RolandKluge** [comment]
Application conditions are working (Right, @fdeckwerth ?), but apart from me and probably Fred, nobody employs them in development projects, currently.

As long as we stick to EA, we should be able to visualize complex application condiitons similarly to the traditional NACs, consisting of at most one OV / link variable per NAC. In the easiest case, each element of a composite NAC should be labeled with an index (similar to EA). This is not very legibible, but should do as a first resort. Additionally, we will have to depict constraint-like ACs similar to the CSPs in TGGs.
