### ISSUE TITLE
Unknown state before deleting project

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-tool#60]
_From @RolandKluge on August 13, 2016 8:20_

When checking out the Demo + Handbook test workspace, I get the following exception, which seems to be rather informative:

(Eclipse runtime, new build process enabled)

```
!ENTRY org.eclipse.core.resources 4 2 2016-08-13 10:18:18.998
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.RuntimeException: org.eclipse.core.runtime.CoreException: Unknown state before deleting project .org.eclipse.jdt.core.external.folders
    at org.gervarro.eclipse.workspace.util.ProjectStateObserver.resourceChanged(ProjectStateObserver.java:44)
    at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
    at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:265)
    at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:369)
    at org.eclipse.core.internal.resources.Resource.broadcastPreDeleteEvent(Resource.java:1885)
    at org.eclipse.core.internal.resources.Resource.delete(Resource.java:767)
    at org.eclipse.core.internal.resources.Project.delete(Project.java:324)
    at org.eclipse.jdt.internal.core.ExternalFoldersManager.cleanUp(ExternalFoldersManager.java:226)
    at org.eclipse.jdt.internal.core.JavaModelManager.saving(JavaModelManager.java:4451)
    at org.eclipse.core.internal.resources.SaveManager.executeLifecycle(SaveManager.java:389)
    at org.eclipse.core.internal.resources.SaveManager$1.run(SaveManager.java:198)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.resources.SaveManager.broadcastLifecycle(SaveManager.java:201)
    at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1186)
    at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1165)
    at org.eclipse.core.internal.resources.DelayedSnapshotJob.run(DelayedSnapshotJob.java:52)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.core.runtime.CoreException: Unknown state before deleting project .org.eclipse.jdt.core.external.folders
    at org.gervarro.eclipse.workspace.util.ProjectStateObserver.throwException(ProjectStateObserver.java:154)
    at org.gervarro.eclipse.workspace.util.ProjectStateObserver.internalHandlePreDelete(ProjectStateObserver.java:145)
    at org.gervarro.eclipse.workspace.util.ProjectStateObserver.resourceChanged(ProjectStateObserver.java:41)
    ... 18 more
```

_Copied from original issue: eMoflon/emoflon#767_

**Comment by RolandKluge** [comment]
_From @gervarro on August 13, 2016 21:15_

Eclipse nicely reports about an inconsistent project manipulation in case of this hidden project, and the ProjectStateObserver is too strict. I am going to fix it in the near future.

**Comment by RolandKluge** [comment]
I guess this issue is done.
